# Generated by Django 3.0 on 2019-12-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=10)),
                ('atomic_number', models.IntegerField(max_length=3)),
                ('atom_mass', models.CharField(max_length=20)),
                ('physical_state', models.CharField(max_length=60)),
                ('chemical_character', models.CharField(max_length=30)),
                ('density', models.CharField(max_length=20)),
                ('melt_temp', models.CharField(max_length=10)),
                ('boiling_temp', models.CharField(max_length=10)),
                ('discover_year', models.CharField(max_length=30)),
                ('discover', models.CharField(max_length=40)),
            ],
        ),
    ]
